
name: CI

on:
   push:
    branches: ["task_container_and_ingestion_step"]
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # ðŸ”¹ Set up Python (adjust version if needed)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # ðŸ”¹ Install dependencies from messy_review_dataset_model/requirements.txt
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt


      - name: Run root Python script
        run: python main.py

      # (Your existing scripts)
      - name: Run notebook
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
